### ISSUE TITLE
Unable to run search.py

### ISSUE THREAD

**Issue by tal** [dnschneid/pysmartblinds#16]
I've been unable to figure out how to get search.py to run on my Mac.

I'm not sure how you included the library but I used `export PYTHONPATH=~/Projects/pysmartblinds/pysmartblinds/`.

After which I got the following error:
```
~/Projects/pysmartblinds/examples master
❯ python3 search.py
Scanning for 10 seconds...Traceback (most recent call last):
  File "/Users/atlastal/Projects/pysmartblinds/pysmartblinds/pysmartblinds.py", line 45, in scan
    gatt.start(reset_on_start=False)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 259, in start
    searchwindowsize=self._search_window_size)
  File "/usr/local/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 204, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/usr/local/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 276, in _spawn
    'executable: %s.' % self.command)
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: gatttool.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "search.py", line 60, in <module>
    main()
  File "search.py", line 49, in main
    macs = scan(SCAN_SECONDS)
  File "search.py", line 23, in scan
    macs = pysmartblinds.scan(seconds)
  File "/Users/atlastal/Projects/pysmartblinds/pysmartblinds/pysmartblinds.py", line 48, in scan
    gatt.stop()
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 281, in stop
    self.disconnect(self._connected_device)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 53, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 419, in disconnect
    if not self._receiver.is_set("disconnected"):
AttributeError: 'NoneType' object has no attribute 'is_set'
```

I'm running `Python 3.7.2`

**Comment by deftdawg** [comment]
@tal You need to install the "bluez" bluetooth support package that provides hcitool and gatttool for your distro.
