### ISSUE TITLE
Implement open_cover and close_cover to be compatible with Amazon Alexa / haaska

### ISSUE THREAD

**Issue by jumpkick** [dnschneid/pysmartblinds#9]
In order to actuate blinds from Alexa via [haaska](https://github.com/mike-grant/haaska), we need to define these methods:
```
def open_cover(self, **kwargs):  # Alexa, turn off blind XYZ
def close_cover(self, **kwargs): # Alexa, turn on blind XYZ
```

Without them we get: 
```
2018-11-28 01:18:46 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=cover, service=close_cover, service_data=entity_id=cover.north_bedroom, service_call_id=eb4ca86cf54144ebb0c9bcef82bdaa3b>
2018-11-28 01:18:46 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event alexa_smart_home[L]: request=namespace=Alexa.PowerController, name=TurnOff, entity_id=cover.north_bedroom, response=namespace=Alexa, name=Response>
2018-11-28 01:18:46 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/cover/__init__.py", line 243, in close_cover
    raise NotImplementedError()
NotImplementedError
```

**Comment by dnschneid** [comment]
Shouldn't this be a bug with haaska, to fall back on tilt when open/close isn't available?  pysmartblinds doesn't support open/close.
